version: '3.8'

services:
  whisper_api:
    build: .
    container_name: whisper_api_transcriber
    # Mapea el puerto 8000 del contenedor al puerto 8000 de tu máquina local
    ports:
      - "8000:8000"
    # Opcional: Restart policy
    restart: always